# Necessary because the switch disabling unwanted insecure key
# replacement in Vagrant 1.7+ is not accepted by earlier versions
Vagrant.require_version ">= 1.7.0"

# these ought to match what is in config.sh
n_machines = 3
ip_prefix = "192.168.48"
ip_suffix_base = 10

require '../vagrant-common.rb'

def configure_vm(host, hostname, ip)
  host.vm.box = VAGRANT_IMAGE
  host.vm.network "private_network", ip: ip

  # Tests rely on hostnames instead of IP addresses:
  host.vm.hostname = hostname
  host.vm.provision :shell, :inline => "echo #{ip} #{hostname} >> /etc/hosts"

  # Disable default Vagrant shared folder, which we don't need:
  host.vm.synced_folder ".", "/vagrant", disabled: true
end

def configure_resolv_conf(host)
  # Fix the resolution errors by using 8.8.8.8
  host.vm.provision :shell, :inline => "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
end


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.memory = 384
    configure_nat_dns(vb)
  end

  # Disable Vagrant 1.7 per host insecure key replacement
  config.ssh.insert_key = false

  (1..n_machines).each do |i|
    config.vm.define "host#{i}" do |host|
      ip_suffix = ip_suffix_base + i
      configure_resolv_conf(host)
      configure_vm(host, "host#{i}", "#{ip_prefix}.#{ip_suffix}")
      cleanup host.vm

      # Only execute once the Ansible provisioner, when all the machines are up and ready:
      if i == n_machines
        host.vm.provision 'ansible' do |ansible|
          ansible.limit = 'all'  # Disable default limit to connect to all the machines
          ansible.playbook = '../tools/config_management/setup_weave-net_test.yml'
        end
      end
    end
  end

end

begin
  load 'Vagrantfile.local'
rescue LoadError
end
